name: New quiz question
description: Create a new question
title: "New question: [REPLACE HERE]"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: Thanks for contributing to our cool quiz!
  - type: input
    id: question
    attributes:
      label: New question
      description: Please give us a cool and exciting question
      placeholder: What was first, the egg or the chicken?
    validations:
      required: true
  - type: input
    id: answer1
    attributes:
      label: Answer 1
      placeholder: Egg
    validations:
      required: true
  - type: input
    id: answer2
    attributes:
      label: Answer 2
      placeholder: Chicken
    validations:
      required: true
  - type: input
    id: answer3
    attributes:
      label: Answers 3
      placeholder: There is no right answer
    validations:
      required: true
  